import exceptions.ArgumentOutOfRange;
import labExercises.Lab10;

public class Main {

    static long[] arr = {1, 2, 3, 4};
    static String naam = "Stijn";

    public static void main(String[] args) throws ArgumentOutOfRange {

        Lab10 l10 = new Lab10();
        l10.runInMain();

    }
}
